### ISSUE TITLE
cards should always be visible when stacked

### ISSUE THREAD

**Issue by creisle** [creisle/quarantined_wizzards#103]
cards should always be visible when stacked even when not brought up

**Comment by areisle** [comment]
this wasn't practical on small devices as can be seen here for a pixel 1 with 20 cards
![20-cards-pixel-1](https://user-images.githubusercontent.com/15241606/80299530-fe7a1f00-8749-11ea-9c51-b5ebcbda39b3.png)

instead more hinting to the user that there is more cards seems to be the way to go
![pixel-2-showing-top-of-row-2-cards](https://user-images.githubusercontent.com/15241606/80299541-12258580-874a-11ea-8382-24ec33a86f27.png)
