### ISSUE TITLE
score isn't showing correctly if no tricks taken

### ISSUE THREAD

**Issue by areisle** [creisle/quarantined_wizzards#54]
if the user takes 0 tricks, the score isn't updated as taken is still null

**Comment by areisle** [comment]
![image](https://user-images.githubusercontent.com/15241606/79627813-6f895900-80f0-11ea-8e3f-efeb50335dae.png)

**Comment by creisle** [comment]
Also ran into this where the score has taken = 0 for everyone

![image](https://user-images.githubusercontent.com/4342641/79628006-d8250580-80f1-11ea-8192-1c5b6d9b42a6.png)

**Comment by creisle** [comment]
the context for the above screen shot

![image](https://user-images.githubusercontent.com/4342641/79628021-0dc9ee80-80f2-11ea-8479-49455601ee47.png)
