### ISSUE TITLE
Unable to pick card on turn

### ISSUE THREAD

**Issue by creisle** [creisle/quarantined_wizzards#68]
![image](https://user-images.githubusercontent.com/4342641/79668886-c2085b00-816c-11ea-819c-e9c706338624.png)

we had 1 socket time out that required a refresh earlier

this issue was not resolved with refresh

**Comment by creisle** [comment]
gameId: LdEMXVSeE

**Comment by creisle** [comment]
the card doesn't exist server side either so the card got played but then the game state wasn't updated and the play card event was not sent

**Comment by creisle** [comment]
the played card did not exist in the trick cards either

**Comment by areisle** [comment]
this happened again on round 8 trick 8 with 4 players; again on second card of trick. the card that disappeared was a jester
